name: Claim Free Games

on: # When to run this workflow
    push: # When you edit this repo

# Uncomment the below lines to enable manual trigger.

#    watch:
#        types: [started] # When repo owner stars this repo

    schedule:
        - cron: "0 0 * * *" # Everyday at 00:00 UTC

jobs:
    claim:
        runs-on: ubuntu-latest

        timeout-minutes: 5 # Automatically stop after 5 minutes

        steps:
            - name: Setup repo
              uses: actions/checkout@v2
              with:
                  repository: "Revadike/epicgames-freebies-claimer"

            - name: Setup Node.js
              uses: actions/setup-node@v1
              
            - name: Install Chrome Deps
              run: sudo apt-get install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
            
            - name: Install dependencies
              run: yarn

            - name: Hotfix for \#4 # https://github.com/xuac/claim-epic-freebies/issues/4
              run: mkdir .egstore

            - name: Get Epic Freebies
              run: yarn start ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} 0 ${{ secrets.SECRETKEY }}
